AlignedSequenceRepresentation: Methods added for - removal of stop codons (conversion to gap codons) - removal of gap codons preserving codon boundaries - trimming of 3' sites to give integer numbers of codons.
SequenceTypeNotSupportedException: new Exception class for sequence type mismatches (e.g. translating AA->DNA, codon stop removal in AA etc)

JUnit tests: Associated tests for the above (all passed.)